### PR TITLE
Eigen v 3.3.7 needed to build electric circuit solver

### PR DESCRIPTION
**Pull request by jprk**
I am not sure where to put it, but the future pull request for electric device powered and charged from overhead wires (the ElecHybrid) optinally needs the Eigen library. The library license should be compatible with the SUMO license, we are explicitly switching off the part that is not MLP2 compatible by defining `EIGEN_MPL2_ONLY` in the code.

The current version of our (private) ElecHybrid branch looks for Eigen in $SUMO_LIBRARIES/eigen_x.x.x

The library consists only of header files, nothing has to be compiled.

Jan

### CODE REVIEW

**Comment by behrisch** [comment]
Can we do this as a submodule? It seems they have a git repo here: https://gitlab.com/libeigen/eigen

**Comment by jprk** [comment]
Definitely. Shall I try it on my repo and let you know? Or do you prefer to
handle it yourself?

-- jan

**Comment by behrisch** [comment]
Please try it out on your side. Thank you.

**Comment by jprk** [comment]
Submodule added, compiles and runs on our side with the development branch of SUMO under Windows, I do not have an easy access to a Linux machine right now, unfortunately.

**Comment by behrisch** [comment]
@jprk Thank you! Since the SUMOLibraries are targeted at the Windows developers there is no need to test it on Linux.

**Comment by jprk** [comment]
Michael, I have just checked a fresh `git clone` from the merged repository and something is wrong with submodules:

```
honza@DESKTOP-HNGQDP8 MINGW64 /d/Temp/MAVEN
$ git clone https://github.com/DLR-TS/SUMOLibraries.git SUMOLibraries.git
Cloning into 'SUMOLibraries.git'...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 79746 (delta 5), reused 27 (delta 3), pack-reused 79711
Receiving objects: 100% (79746/79746), 905.67 MiB | 20.02 MiB/s, done.
Resolving deltas: 100% (33708/33708), done.
Updating files: 100% (74801/74801), done.

honza@DESKTOP-HNGQDP8 MINGW64 /d/Temp/MAVEN
$ cd SUMOLibraries.git

honza@DESKTOP-HNGQDP8 MINGW64 /d/Temp/MAVEN/SUMOLibraries.git (master)
$ git submodule
fatal: no submodule mapping found in .gitmodules for path '3rdPartyLibs/grpc/benchmark-1.5.0/third_party/googletest/src'

honza@DESKTOP-HNGQDP8 MINGW64 /d/Temp/MAVEN/SUMOLibraries.git (master)
$ git submodule init
fatal: No url found for submodule path '3rdPartyLibs/grpc/benchmark-1.5.0/third_party/googletest/src' in .gitmodules
```

Indeed the directory `3rdPartyLibs/grpc/benchmark-1.5.0/third_party/googletest/src` is empty on my system.

If I look for staged files, and look for directories that should contain submodules, I get

```
honza@DESKTOP-HNGQDP8 MINGW64 /d/Temp/MAVEN/SUMOLibraries.git (master)
$ git ls-files --stage | grep 160000
160000 ba513d2c9525a7c986c115ed5d603f2cf17c6016 0       3rdPartyLibs/grpc/benchmark-1.5.0/third_party/googletest/src
100644 63276de09042c5ca3fe693b1dc309e1600005070 0       3rdPartyLibs/protobuf-3.9.1/src/google/protobuf/compiler/cpp/cpp_file.cc
160000 21ae2afd4edaa1b69782c67a54182d34efe43f9c 0       eigen
```

Doing `git rm 3rdPartyLibs/grpc/benchmark-1.5.0/third_party/googletest/src`, but I am not sure if it is the right thing to do.

**Comment by jprk** [comment]
Just checked other options that would result in a smooth clone and verified that issuing

 ```
git clone --recurse-submodules https://github.com/DLR-TS/SUMOLibraries
```

works (git version 2.24.0.windows.2).

**Comment by behrisch** [comment]
@palvarezlopez Can you tell us something about the state of submodules in SUMOLibraries? I thought that we did not use them up to now?

**Comment by palvarezlopez** [comment]
@behrisch until now I didn't use submodules in SUMOLibraries.

**Comment by behrisch** [comment]
OK, I could reproduce the dangling submodule on various checkouts here but we will not fix this before the release and the whole grpc is going to be removed afterwards.

**Pull request merged**
